CREATE TABLE DEPARTMENT(
  DEP_ID VARCHAR(6) PRIMARY KEY,
  D_NAME TEXT NOT NULL,
  HOD TEXT NOT NULL
);
CREATE TABLE STUDENTS(
  STU_ID INT PRIMARY KEY,
  NAME TEXT NOT NULL,
  DOB DATE NOT NULL,
  GENDER CHAR(1) NOT NULL
);
CREATE TABLE INSTRUCTIONS(
  INS_ID VARCHAR(4) PRIMARY KEY,
  I_NAME TEXT NOT NULL,
  DEP_ID VARCHAR(6) NOT NULL,
  FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);
CREATE TABLE COURSE(
  C_CODE VARCHAR(6) PRIMARY KEY,
  C_NAME TEXT NOT NULL,
  CREDIT INT(2) NOT NULL,
  DEP_ID VARCHAR(6) NOT NULL,
  FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);
CREATE TABLE ENROLLMENT(
  EN_ID VARCHAR(10) PRIMARY KEY,
  STU_ID INT NOT NULL,
  C_CODE VARCHAR(6) NOT NULL,
  GRADE TEXT NOT NULL,
  FOREIGN KEY (STU_ID) REFERENCES STUDENTS(STU_ID),
  FOREIGN KEY (C_CODE) REFERENCES COURSE(C_CODE)
);
INSERT INTO DEPARTMENT VALUES ("D01","CSE","AAA"), ("D02","MATHS","BBB");
INSERT INTO STUDENTS VALUES (1,"ABC","01-01-2001","M"),(2,"DEF","02-02-2002","M");
INSERT INTO INSTRUCTIONS VALUES ("I101","XYZ","D01"), ("I102","ZYX","D02");
INSERT INTO COURSE VALUES ("CSE101","COMPUTER SCIENCE",3,"D01"), ("MTS102","MATHEMATICS",4,"D02");
INSERT INTO ENROLLMENT VALUES ("E202301",1,"CSE101","A"), ("E20231",1,"MTS102","A+"),("E202302",2,"CSE101","A"),("E20232",2,"MTS102","B");


